services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  flask-app:
    build: ./flask-app
    container_name: flask-app
    ports:
      - "8088:8088"
      - "1935:1935"
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - /home/kdresdell/Documents/DEV/itool/flask-app/iptv_data:/nginx/app/iptv_data
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "80:8096"
    volumes:
      - /mnt/media:/media
      - /home/kdresdell/jellyfin_config:/config
      - /home/kdresdell/jellyfin_cache:/cache
    restart: unless-stopped

 
