version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"

  flask-app:
    build: ./flask-app
    container_name: flask-app
    ports:
      - "8080:8080"
      - "1935:1935"
      - "5000:5000"
    volumes:
      - ./home/kdresdell/Videos:/nginx/recordings
    depends_on:
      - redis
